import { Item } from "./item";

export let products: Item[] = [
  new Item(
    "1001",
    "Mona Jesper",
    "https://dl.dropboxusercontent.com/s/la5l4cli6mfnwvo/MonaJesper_100x100.png?dl=0",
    "https://dl.dropboxusercontent.com/s/8w73mk87bi1ueqd/MonaJesper_300x300.png?dl=0",
    "Painting of Mona Lisa but with the face of Jesper.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
    "Long description",
    500000,
    "S",
    1,
    "Info",
    "Add",
    1
  ),
  new Item(
    "1002",
    "Dra hem",
    "https://dl.dropboxusercontent.com/s/ga04etuprskplb1/02_100x100.png?dl=0",
    "https://dl.dropboxusercontent.com/s/gmrdnh8h6p1fyjc/02_300x300.png?dl=0",
    "Abstract colorful painting with watercolors on white canvas.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
    "long description",
    799,
    "L",
    3,
    "Info",
    "Add",
    1
  ),
  new Item(
    "1003",
    "Girl on a cliff",
    "https://dl.dropboxusercontent.com/s/7r34tpp7ul6cezf/03_100x100.png?dl=0",
    "https://dl.dropboxusercontent.com/s/h2vqhifuk0pa3xz/03_300x300.png?dl=0",
    "Oil painting of a hand holding a short cigarette.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
    "long description",
    5999,
    "M",
    2,
    "Info",
    "Add",
    1
  ),
  new Item(
    "1004",
    "Gunnar painting",
    "https://dl.dropboxusercontent.com/s/i5dtl88rueme6ap/04_100x100.png?dl=0",
    "https://dl.dropboxusercontent.com/s/cdm2nguo2h1xmix/04_300x300.png?dl=0",
    "Childish painting of a tree on white canvas in green and yellow watercolor.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
    "long description",
    7999,
    "S",
    1,
    "Info",
    "Add",
    1
  ),
  new Item(
    "1005",
    "Routsalainen päivänkulla",
    "https://dl.dropboxusercontent.com/s/4hhksq5ax6tqre5/05_100x100.png?dl=0",
    "https://dl.dropboxusercontent.com/s/ecu1lnskrel5ri6/05_300x300.png?dl=0",
    "A painting depicting Swedish gold of day in an abstract way.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
    "long description",
    6999,
    "L",
    3,
    "Info",
    "Add",
    1
  ),
  new Item(
    "1006",
    "Brexit",
    "https://dl.dropboxusercontent.com/s/u9720cpjzq8bu76/06_100x100.png?dl=0",
    "https://dl.dropboxusercontent.com/s/735dvsqmsebsvrs/06_300x300.png?dl=0",
    "A painting depicting a kneeling human made out of flowers.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
    "long description",
    6677,
    "L",
    3,
    "Info",
    "Add",
    1
  ),
  new Item(
    "1007",
    "Boris Johansson",
    "https://dl.dropboxusercontent.com/s/xbhy2p01dgxuraj/07_100x100.png?dl=0",
    "https://dl.dropboxusercontent.com/s/5ghkiroa65daeio/07_300x300.png?dl=0",
    "A painting of a banana made out of flowers floating in dark space.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
    "long description",
    8999,
    "M",
    2,
    "Info",
    "Add",
    1
  ),
  new Item(
    "1008",
    "Fäsh n Cräsp",
    "https://dl.dropboxusercontent.com/s/4i7egjwpc7hh8zv/08_100x100.png?dl=0",
    "https://dl.dropboxusercontent.com/s/rfa811thmliz012/08_300x300.png?dl=0",
    "A drawing of a frog with nerves instead of feet.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
    "long description",
    4599,
    "M",
    2,
    "Info",
    "Add",
    1
  ),
  new Item(
    "1009",
    "Banan på ett träd",
    "https://dl.dropboxusercontent.com/s/30ubv95ckmqul52/09_100x100.png?dl=0",
    "https://dl.dropboxusercontent.com/s/845ogxnnrkhs8nt/09_300x300.png?dl=0",
    "A collage of random images composed in an abstract way on paper.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
    "long description",
    1999,
    "L",
    3,
    "Info",
    "Add",
    1
  ),
  new Item(
    "1010",
    "Yxskaft på en kudde",
    "https://dl.dropboxusercontent.com/s/st1ejx1j8ac81uh/10_100x100.png?dl=0",
    "https://dl.dropboxusercontent.com/s/w1i94aloaz6svj5/10_300x300.png?dl=0",
    "An abstract painting of color strokes in black, cyan, yellow and red on white canvas.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
    "long description",
    29,
    "S",
    1,
    "Info",
    "Add",
    1
  ),
];
